### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by Velocitractor00** [midblue/timezone-bot#8]
Hi, I seem to be getting an error now when using this bot, I think I had some issues on my billing account but those are fixed now (card was expired) - but for some reason it wont look-up users from the list I've attached the message it outputs: 

> Loaded 24 saved users
Connected to Discord
(node:4644) UnhandledPromiseRejectionWarning: RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT-1
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at Object.currentTimeAt (/home/pi/Downloads/TZ/scripts/format.js:7:37)
    at Object.values.reduce (/home/pi/Downloads/TZ/scripts/interact.js:160:34)
    at Array.reduce (<anonymous>)
    at Object.listUsers (/home/pi/Downloads/TZ/scripts/interact.js:158:60)
    at Client.discordClient.on (/home/pi/Downloads/TZ/index.js:71:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/pi/Downloads/TZ/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/pi/Downloads/TZ/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
(node:4644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4644) UnhandledPromiseRejectionWarning: RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT-1
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at Object.currentTimeAt (/home/pi/Downloads/TZ/scripts/format.js:7:37)
    at Object.values.reduce (/home/pi/Downloads/TZ/scripts/interact.js:160:34)
    at Array.reduce (<anonymous>)
    at Object.listUsers (/home/pi/Downloads/TZ/scripts/interact.js:158:60)
    at Client.discordClient.on (/home/pi/Downloads/TZ/index.js:71:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/pi/Downloads/TZ/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/pi/Downloads/TZ/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
(node:4644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

any help de-bugging would be greatly appreciated -thankyou

**Comment by midblue** [comment]
Oh interesting, looking [here](https://github.com/webpack/webpack/issues/9818) it looks like it's an issue with JS's toLocaleTimeString function not accepting some specific time zone codes. 

From the spec:
```The options property timeZone in the DateTimeFormat constructor, provided that the additional acceptable input values are case-insensitive matches of Zone or Link identifiers in the IANA time zone database and are canonicalized to Zone identifiers in the casing used in the database for the timeZone property of the object returned by DateTimeFormat.resolvedOptions, except that "Etc/GMT" shall be canonicalized to "UTC".
```

My guess is that we could safely replace('Etc/GMT', 'UTC') on the user's timezone before calling toLocaleDateString and that would fix it. I'll put it on my to-do list, but if you feel confident enough, feel free to try it out beforehand.

**Comment by Velocitractor00** [comment]
so this would be in the users.json change anything that says Etc/GMT to say UTC?

**Comment by Velocitractor00** [comment]
it worked! - we are back in business -ty very much for looking over that :)

**Comment by midblue** [comment]
Great! I just pushed a version of the code with a full fix that _should_ prevent it from happening in the future. I haven't tested it yet, but it seems straightforward enough.
